### ISSUE TITLE
Crash during startup (stage 6/7), pointed at ForgeRegistry

### ISSUE THREAD

**Issue by Mongole** [kyeiti/UndergroundBiomesConstructs#10] opened 2018-05-21 23:35 UTC
https://paste.ee/p/HbDsG

Using Forge 14.23.3.2702, happens with underground biomes 1.1.0 - 1.1.1 fixed

Before the crash occours it logs in Registry Block: Override did not have an associated owner object to thermal foundation ore redstone

**Comment by Sinxar** [comment] 2018-05-22 00:26
https://paste.ee/p/CiuPm

Same error with full latest.log

**Comment by Sanofus** [comment] 2018-05-22 00:53
Duplicate of my issue. https://github.com/kyeiti/UndergroundBiomesConstructs/issues/9

**Comment by kyeiti** [comment] 2018-05-22 18:05
Closing in favor of #9

**Closed by kyeiti** 2018-05-22 18:05 UTC
